Request money on Sandbox if balance zero. (bunq/tinker_csharp#7)
bunq/tinker_csharp pull request #8
Opened 2018-04-04 21:50 UTC by JordyHeemskerk

2018-04-05 11:43 UTC, OGKevin requested changes
Minor changes.

2018-04-05 11:43 UTC, OGKevin commented on TinkerSrc/Lib/BunqLib.cs
> +            if (ApiEnvironmentType.SANDBOX.Equals(EnvironmentType)
Logic can be extracted in its own separate method.

2018-04-05 11:43 UTC, OGKevin commented on TinkerSrc/Lib/BunqLib.cs
> +            RequestSpendingMoneyIfNeeded();
TODO: bunq/sdk_csharp#89

after sdk update.

2018-04-12 12:34 UTC, JordyHeemskerk commented
@OGKevin moving UserContext refresh to new issue. Implemented comments.

2018-04-12 17:13 UTC, OGKevin approved these changes
👌

2018-04-12 17:13 UTC, merged

2018-04-12 17:14 UTC, OGKevin commented
@andrederoos